# -*- coding: utf-8 -*-
"""OTI_Application.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cGvTe8r_3G7YMjvqi4nqj7Bu4dz2pHsT
"""

from random import randint
import numpy as np

def main():
  First_line = ["_","_","_"]
  Second_line = ["_","_","_"]
  Third_line = ["_","_","_"]
  Board = np.array([[First_line],[Second_line],[Third_line]])

  def Play_Again():

    var = input("\n\nDo you want to play again?\nEnter 'yes' or 'no'\n")

    while var != "yes":
      if var != "no":
        var = input("Try again. Do you want to play again?\nEnter 'yes' or 'no'\n")
      else:
        break

    if var == "no":
      print("Thanks for playing!")
      quit()

    else:
      main()

    return

  def Put_X(X):
    if X == 1:
      First_line[0] = "X"
    if X == 2:
      First_line[1] = "X"
    if X == 3:
      First_line[2] = "X"
    if X == 4:
      Second_line[0] = "X"
    if X == 5:
      Second_line[1] = "X"
    if X == 6:
      Second_line[2] = "X"
    if X == 7:
      Third_line[0] = "X"
    if X == 8:
      Third_line[1] = "X"
    if X == 9:
      Third_line[2] = "X"
    Board = np.array([[First_line],[Second_line],[Third_line]])
    print("\n")

    for i in Board:
      for j in i:
        print(j, end=" ")
      print()

    if First_line == ["X","X","X"] or Second_line == ["X","X","X"] or Third_line == ["X","X","X"]:
      print("\nPlayer wins!")
      Play_Again()
    else:
      for i in range(0,3):
        if First_line[i] == "X" and Second_line[i] == "X" and Third_line[i] == "X":
          print("\nPlayer wins!")
          Play_Again()
      if First_line[0] == "X" and Second_line[1] == "X" and Third_line[2] == "X":
        print("\nPlayer wins!")
        Play_Again()
      else:
        if First_line[2] == "X" and Second_line[1] == "X" and Third_line[0] == "X":
          print("\nPlayer wins!")
          Play_Again()
        else:
          return

  def Put_O(O):
    if O == 1:
      First_line[0] = "O"
    if O == 2:
      First_line[1] = "O"
    if O == 3:
      First_line[2] = "O"
    if O == 4:
      Second_line[0] = "O"
    if O == 5:
      Second_line[1] = "O"
    if O == 6:
      Second_line[2] = "O"
    if O == 7:
      Third_line[0] = "O"
    if O == 8:
      Third_line[1] = "O"
    if O == 9:
      Third_line[2] = "O"
    Board = np.array([[First_line],[Second_line],[Third_line]])
    print("\n")
    for i in Board:
      for j in i:
        print(j, end=" ")
      print()
    print("\n")
    if First_line == ["O","O","O"] or Second_line == ["O","O","O"] or Third_line == ["O","O","O"]:
      print("\nComputer wins!")
      Play_Again()
    else:
      for i in range(0,3):
        if First_line[i] == "O" and Second_line[i] == "O" and Third_line[i] == "O":
          print("\nComputer wins!")
          Play_Again()
      if First_line[0] == "O" and Second_line[1] == "O" and Third_line[2] == "O":
        print("\nComputer wins!")
        Play_Again()
      else:
        if First_line[2] == "O" and Second_line[1] == "O" and Third_line[0] == "O":
          print("\nComputer wins!")
          Play_Again()
        else:
          return

  val = input("Would you like to go first or would you like for the computer to go first?\nEnter 'me' or 'computer'\n")

  while val != "me":
    if val != "computer":
      val = input("Try again. Would you like to go first or would you like for the computer to go first?\nEnter 'me' or 'computer'\n")
    else:
      break

  if val == "me":

    while True:
      X1 = int(input("Where would you like to put your first 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X1 in range(1,10):
        break
      else:
        print("Try again! Please put a number between 1 and 9\n")

    Put_X(X1)

    while True:
      O1 = randint(1,9)
      if O1 != X1:
        break
      else:
        O1 = randint(1,9)

    Put_O(O1)

    while True:
      X2 = int(input("Where would you like to put your second 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X2 == X1 or X2 == O1:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X2 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X2)

    while True:
      O2 = randint(1,9)
      if O2 == X1 or O2 == X2 or O2 == O1:
        pass
      else:
        break

    Put_O(O2)

    while True:
      X3 = int(input("Where would you like to put your third 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X3 == X1 or X3 == O1 or X3 == X2 or X3 == O2:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X3 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X3)

    while True:
      O3 = randint(1,9)
      if O3 == X1 or O3 == X2 or O3 == O1 or O3 == O2 or O3 == X3:
        pass
      else:
        break

    Put_O(O3)

    while True:
      X4 = int(input("Where would you like to put your fourth 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X4 == X1 or X4 == O1 or X4 == X2 or X4 == O2 or X4 == X3 or X4 == O3:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X4 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X4)

    while True:
      O4 = randint(1,9)
      if O4 == X1 or O4 == X2 or O4 == O1 or O4 == O2 or O4 == X3 or O4 == X4 or O4 == O3:
        pass
      else:
        break

    Put_O(O4)

    while True:
      X5 = int(input("Where would you like to put your fifth 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X5 == X1 or X5 == O1 or X5 == X2 or X5 == O2 or X5 == X3 or X5 == O3 or X5 == X4 or X5 == O4:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X5 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X5)

    print("\nLooks like it's a tie!\n")
    Play_Again()

  else:
    O1 = randint(1,9)

    Put_O(O1)

    while True:
      X1 = int(input("Where would you like to put your first 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X1 == O1:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X1 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X1)

    while True:
      O2 = randint(1,9)
      if O2 == X1 or O2 == O1:
        pass
      else:
        break

    Put_O(O2)

    while True:
      X2 = int(input("Where would you like to put your second 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X2 == X1 or X2 == O1 or X2 == O2:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X2 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X2)

    while True:
      O3 = randint(1,9)
      if O3 == X1 or O3 == X2 or O3 == O1 or O3 == O2:
        pass
      else:
        break

    Put_O(O3)

    while True:
      X3 = int(input("Where would you like to put your third 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X3 == X1 or X3 == O1 or X3 == X2 or X3 == O2 or X3 == O3:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X3 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X3)

    while True:
      O4 = randint(1,9)
      if O4 == X1 or O4 == X2 or O4 == O1 or O4 == O2 or O4 == X3 or O4 == O3:
        pass
      else:
        break

    Put_O(O4)

    while True:
      X4 = int(input("Where would you like to put your fourth 'X'?\n\n1 2 3\n4 5 6\n7 8 9\n\nType the number of the space you want to put your 'X'\n"))
      if X4 == X1 or X4 == O1 or X4 == X2 or X4 == O2 or X4 == X3 or X4 == O3 or X4 == O4:
        print("Whoops, that space is full! Try again!\n\n")
      else:
        if X4 in range(1,10):
          break
        else:
          print("Try again! Please put a number between 1 and 9\n")

    Put_X(X4)

    while True:
      O5 = randint(1,9)
      if O5 == X1 or O5 == X2 or O5 == O1 or O5 == O2 or O5 == X3 or O5 == X4 or O5 == O3 or O5 == O4:
        pass
      else:
        break

    Put_O(O5)

    print("\nLooks like it's a tie!\n")
    Play_Again()

  return

main()

